project_name: idsec-sdk
version: 2
builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "typo"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

release:
  github:
    owner: cyberark
    name: idsec-sdk-golang
  replace_existing_artifacts: true

