// Package api provides the main IDSEC SDK API interface for accessing all IDSEC services
// Code generated by genservices; DO NOT EDIT.
// Automatically generated Idsec API for all SDK services.
// Each service can define a module init to register its config alongside a ServiceGenerator function
// in the IDSEC SDK Golang. This package serves as the central entry point for interacting
// with various IDSEC services including SIA, SecHub, PCloud, Identity, and other components.
//
// The IdsecAPI struct acts as a service factory and registry, managing authenticators,
// service instances, and configuration profiles. It provides lazy loading of services,
// meaning services are only instantiated when first accessed, and subsequent calls
// return the cached instance.
//
// Key features:
//   - Centralized access to all IDSEC services
//   - Lazy loading and caching of service instances
//   - Authenticator management and distribution to services
//   - Profile-based configuration management
//   - Service dependency injection with authenticators
//   - Consistent error handling across all services
//
// The API supports multiple authenticators that are automatically distributed to
// services based on their configuration requirements. Each service specifies
// required and optional authenticators, and the API ensures the appropriate
// authenticators are provided during service initialization.
//
// Example:
//
//	// Create authenticators
//	ispAuth := &auth.IdsecISPAuth{...}
//	authenticators := []auth.IdsecAuth{ispAuth}
//
//	// Create API instance
//	api, err := NewIdsecAPI(authenticators, nil) // nil uses default profile
//	if err != nil {
//		// handle error
//	}
//
//	// Access services (lazy loaded)
//	ssoService, err := api.SiaSso()
//	if err != nil {
//		// handle error
//	}
//
//	// Get specific authenticator
//	auth, err := api.Authenticator("isp")
//	if err != nil {
//		// handle error
//	}
package api

import (
	"fmt"
	"sync"

	"github.com/cyberark/idsec-sdk-golang/pkg/auth"
	"github.com/cyberark/idsec-sdk-golang/pkg/models"
	"github.com/cyberark/idsec-sdk-golang/pkg/profiles"
	"github.com/cyberark/idsec-sdk-golang/pkg/services"

	assets "github.com/cyberark/idsec-sdk-golang/pkg/services/access/assets"
	aws "github.com/cyberark/idsec-sdk-golang/pkg/services/cce/aws"
	azure "github.com/cyberark/idsec-sdk-golang/pkg/services/cce/azure"
	gcp "github.com/cyberark/idsec-sdk-golang/pkg/services/cce/gcp"
	connectors "github.com/cyberark/idsec-sdk-golang/pkg/services/cmgr/connectors"
	networks "github.com/cyberark/idsec-sdk-golang/pkg/services/cmgr/networks"
	poolcomponents "github.com/cyberark/idsec-sdk-golang/pkg/services/cmgr/poolcomponents"
	poolidentifiers "github.com/cyberark/idsec-sdk-golang/pkg/services/cmgr/poolidentifiers"
	pools "github.com/cyberark/idsec-sdk-golang/pkg/services/cmgr/pools"
	authprofiles "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/authprofiles"
	directories "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/directories"
	policies "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/policies"
	roles "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/roles"
	users "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/users"
	webapps "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/webapps"
	pamshaccounts "github.com/cyberark/idsec-sdk-golang/pkg/services/pamsh/pamshaccounts"
	pamshsafes "github.com/cyberark/idsec-sdk-golang/pkg/services/pamsh/pamshsafes"
	accounts "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/accounts"
	applications "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/applications"
	platforms "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/platforms"
	safes "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/safes"
	targetplatforms "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/targetplatforms"
	usergroups "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/usergroups"
	users2 "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/users"
	policy "github.com/cyberark/idsec-sdk-golang/pkg/services/policy"
	cloudaccess "github.com/cyberark/idsec-sdk-golang/pkg/services/policy/cloudaccess"
	db "github.com/cyberark/idsec-sdk-golang/pkg/services/policy/db"
	groupaccess "github.com/cyberark/idsec-sdk-golang/pkg/services/policy/groupaccess"
	k8s "github.com/cyberark/idsec-sdk-golang/pkg/services/policy/k8s"
	vm "github.com/cyberark/idsec-sdk-golang/pkg/services/policy/vm"
	cloudaccess2 "github.com/cyberark/idsec-sdk-golang/pkg/services/sca/cloudaccess"
	discovery "github.com/cyberark/idsec-sdk-golang/pkg/services/sca/discovery"
	groupaccess2 "github.com/cyberark/idsec-sdk-golang/pkg/services/sca/groupaccess"
	k8s2 "github.com/cyberark/idsec-sdk-golang/pkg/services/sca/k8s"
	configurations "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/configurations"
	filters "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/filters"
	scans "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/scans"
	secrets "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/secrets"
	secretstores "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/secretstores"
	serviceinfo "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/serviceinfo"
	syncpolicies "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/syncpolicies"
	access "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/access"
	certificates "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/certificates"
	db2 "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/db"
	dbstrongaccounts "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/dbstrongaccounts"
	doctor "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/doctor"
	k8s3 "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/k8s"
	dbsecrets "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/secretsdb"
	vmsecrets "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/secretsvm"
	settings "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/settings"
	shortenedconnectionstring "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/shortenedconnectionstring"
	ssh "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/ssh"
	sshca "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/sshca"
	sso "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/sso"
	db3 "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/workspacesdb"
	targetsets "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/workspacestargetsets"
	sessionactivities "github.com/cyberark/idsec-sdk-golang/pkg/services/sm/sessionactivities"
	sessions "github.com/cyberark/idsec-sdk-golang/pkg/services/sm/sessions"
)

// serviceCache holds the services an IdsecAPI has built.
//
// The cache is held by pointer rather than inlined into IdsecAPI so that
// IdsecAPI stays copyable. A mutex placed in IdsecAPI directly would make the
// struct impossible to copy without tripping go vet's copylocks check, and
// consumers embed IdsecAPI by value. Holding it by pointer also keeps the
// existing behaviour that a copied IdsecAPI shares one cache, since a map field
// was already a reference.
type serviceCache struct {
	lock     sync.Mutex
	services map[string]*services.IdsecService
}

// service returns the cached service registered under name, building and
// caching it on first use.
//
// The lock is held across the build so that two goroutines asking for the same
// service concurrently receive the same instance. Building under the lock costs
// the second caller a wait, but the alternative is for both to authenticate and
// connect a service and for one of them to be thrown away.
//
// Parameters:
//   - name: The service's registered name
//   - build: Creates the service, called only when it is not already cached
//
// Returns the cached or newly built service, or an error if build fails.
func (c *serviceCache) service(
	name string,
	build func() (services.IdsecService, error),
) (*services.IdsecService, error) {
	c.lock.Lock()
	defer c.lock.Unlock()
	if cached, ok := c.services[name]; ok {
		return cached, nil
	}
	built, err := build()
	if err != nil {
		return nil, err
	}
	c.services[name] = &built
	return &built, nil
}

// IdsecAPI wraps different API functionality of Idsec Services.
//
// IdsecAPI serves as the central entry point and service factory for all IDSEC services.
// It manages authenticators, service instances, and configuration profiles, providing
// a unified interface for accessing various IDSEC components including SIA, SecHub,
// PCloud, Identity, and other services.
//
// The struct implements lazy loading for services - each service is only instantiated
// when first accessed through its corresponding method. Subsequent calls return the
// cached instance, ensuring efficient resource usage and consistent service state.
//
// Service creation follows a dependency injection pattern where authenticators are
// automatically distributed to services based on their configuration requirements.
// Each service specifies required and optional authenticators, and IdsecAPI ensures
// the appropriate authenticators are provided during initialization.
type IdsecAPI struct {
	authenticators []auth.IdsecAuth
	services       *serviceCache
	profile        *models.IdsecProfile
}

// NewIdsecAPI creates a new IdsecAPI instance with the provided authenticators and profile.
//
// Initializes a new IdsecAPI instance that serves as the central access point for all
// IDSEC services. The instance manages the provided authenticators and distributes them
// to services as needed. If no profile is provided (nil), the default profile is
// loaded automatically.
//
// The services map is initialized empty and services are created lazily when first
// accessed through their respective getter methods. This approach ensures optimal
// resource usage and faster startup times.
//
// Parameters:
//   - authenticators: Slice of authenticators to be used by services. Each service
//     will receive the authenticators it requires based on its configuration
//   - profile: Configuration profile to use. If nil, the default profile is loaded
//     automatically using the default profile loader
//
// Returns a pointer to the initialized IdsecAPI instance, or an error if the default
// profile cannot be loaded when profile is nil.
//
// Example:
//
//	// With explicit profile
//	profile := &models.IdsecProfile{...}
//	api, err := NewIdsecAPI(authenticators, profile)
//
//	// With default profile (recommended)
//	api, err := NewIdsecAPI(authenticators, nil)
//	if err != nil {
//		// handle profile loading error
//	}
func NewIdsecAPI(authenticators []auth.IdsecAuth, profile *models.IdsecProfile) (*IdsecAPI, error) {
	var err error
	if profile == nil {
		profile, err = (*profiles.DefaultProfilesLoader()).LoadDefaultProfile()
		if err != nil {
			return nil, err
		}
	}
	return &IdsecAPI{
		authenticators: authenticators,
		services:       &serviceCache{services: make(map[string]*services.IdsecService)},
		profile:        profile,
	}, nil
}

// loadServiceAuthenticators filters and returns authenticators required by a service configuration.
//
// This internal method processes the API's authenticator collection and returns only
// those authenticators that are required or optional for the specified service.
// Required authenticators are processed first, followed by optional authenticators.
//
// The method ensures that services receive only the authenticators they need,
// following the dependency injection pattern. This approach provides better
// security isolation and cleaner service initialization.
//
// Parameters:
//   - config: Service configuration specifying required and optional authenticator names
//
// Returns a slice of authenticators that match the service's requirements.
// If no matching authenticators are found, returns an empty slice.
func (api *IdsecAPI) loadServiceAuthenticators(config services.IdsecServiceConfig) []auth.IdsecAuth {
	var authenticators []auth.IdsecAuth
	for _, authenticator := range api.authenticators {
		for _, name := range config.RequiredAuthenticatorNames {
			if authenticator.AuthenticatorName() == name {
				authenticators = append(authenticators, authenticator)
			}
		}
	}
	for _, authenticator := range api.authenticators {
		for _, name := range config.OptionalAuthenticatorNames {
			if authenticator.AuthenticatorName() == name {
				authenticators = append(authenticators, authenticator)
			}
		}
	}
	return authenticators
}

// Authenticator returns the authenticator with the specified name from the IdsecAPI instance.
//
// Searches through the API's authenticator collection and returns the first
// authenticator that matches the specified name. This method provides access
// to specific authenticators for custom operations or debugging purposes.
//
// The search is case-sensitive and matches the exact authenticator name as
// returned by the authenticator's AuthenticatorName() method.
//
// Parameters:
//   - authenticatorName: The exact name of the authenticator to retrieve
//
// Returns the matching authenticator, or an error if no authenticator with
// the specified name is found.
//
// Example:
//
//	ispAuth, err := api.Authenticator("isp")
//	if err != nil {
//		// handle authenticator not found
//	}
//	// use ispAuth for custom operations
func (api *IdsecAPI) Authenticator(authenticatorName string) (auth.IdsecAuth, error) {
	for _, authenticator := range api.authenticators {
		if authenticator.AuthenticatorName() == authenticatorName {
			return authenticator, nil
		}
	}
	return nil, fmt.Errorf("%s is not supported or not found", authenticatorName)
}

// Profile returns the profile associated with the IdsecAPI instance.
//
// Provides access to the configuration profile that was set during API initialization.
// The profile contains environment-specific settings, endpoints, and other configuration
// parameters used by the various IDSEC services.
//
// The returned profile is the same instance that was either explicitly provided to
// NewIdsecAPI or automatically loaded as the default profile when nil was passed.
//
// Returns a pointer to the IdsecProfile instance. The profile is never nil for a
// properly initialized IdsecAPI instance.
//
// Example:
//
//	profile := api.Profile()
//	fmt.Printf("Using profile: %s\n", profile.ProfileName)
func (api *IdsecAPI) Profile() *models.IdsecProfile {
	return api.profile
}

func (api *IdsecAPI) AccessAssets() (*assets.IdsecAccessAssetsService, error) {
	service, err := api.services.service(assets.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return assets.ServiceGenerator(api.loadServiceAuthenticators(assets.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*assets.IdsecAccessAssetsService), nil
}

func (api *IdsecAPI) CceAws() (*aws.IdsecCCEAWSService, error) {
	service, err := api.services.service(aws.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return aws.ServiceGenerator(api.loadServiceAuthenticators(aws.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*aws.IdsecCCEAWSService), nil
}

func (api *IdsecAPI) CceAzure() (*azure.IdsecCCEAzureService, error) {
	service, err := api.services.service(azure.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return azure.ServiceGenerator(api.loadServiceAuthenticators(azure.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*azure.IdsecCCEAzureService), nil
}

func (api *IdsecAPI) CceGcp() (*gcp.IdsecCCEGCPService, error) {
	service, err := api.services.service(gcp.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return gcp.ServiceGenerator(api.loadServiceAuthenticators(gcp.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*gcp.IdsecCCEGCPService), nil
}

func (api *IdsecAPI) CmgrConnectors() (*connectors.IdsecCmgrConnectorsService, error) {
	service, err := api.services.service(connectors.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return connectors.ServiceGenerator(api.loadServiceAuthenticators(connectors.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*connectors.IdsecCmgrConnectorsService), nil
}

func (api *IdsecAPI) CmgrNetworks() (*networks.IdsecCmgrNetworksService, error) {
	service, err := api.services.service(networks.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return networks.ServiceGenerator(api.loadServiceAuthenticators(networks.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*networks.IdsecCmgrNetworksService), nil
}

func (api *IdsecAPI) CmgrPoolcomponents() (*poolcomponents.IdsecCmgrPoolComponentsService, error) {
	service, err := api.services.service(poolcomponents.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return poolcomponents.ServiceGenerator(api.loadServiceAuthenticators(poolcomponents.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*poolcomponents.IdsecCmgrPoolComponentsService), nil
}

func (api *IdsecAPI) CmgrPoolidentifiers() (*poolidentifiers.IdsecCmgrPoolIdentifiersService, error) {
	service, err := api.services.service(poolidentifiers.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return poolidentifiers.ServiceGenerator(api.loadServiceAuthenticators(poolidentifiers.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*poolidentifiers.IdsecCmgrPoolIdentifiersService), nil
}

func (api *IdsecAPI) CmgrPools() (*pools.IdsecCmgrPoolsService, error) {
	service, err := api.services.service(pools.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return pools.ServiceGenerator(api.loadServiceAuthenticators(pools.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*pools.IdsecCmgrPoolsService), nil
}

func (api *IdsecAPI) IdentityAuthprofiles() (*authprofiles.IdsecIdentityAuthProfilesService, error) {
	service, err := api.services.service(authprofiles.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return authprofiles.ServiceGenerator(api.loadServiceAuthenticators(authprofiles.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*authprofiles.IdsecIdentityAuthProfilesService), nil
}

func (api *IdsecAPI) IdentityDirectories() (*directories.IdsecIdentityDirectoriesService, error) {
	service, err := api.services.service(directories.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return directories.ServiceGenerator(api.loadServiceAuthenticators(directories.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*directories.IdsecIdentityDirectoriesService), nil
}

func (api *IdsecAPI) IdentityPolicies() (*policies.IdsecIdentityPoliciesService, error) {
	service, err := api.services.service(policies.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return policies.ServiceGenerator(api.loadServiceAuthenticators(policies.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*policies.IdsecIdentityPoliciesService), nil
}

func (api *IdsecAPI) IdentityRoles() (*roles.IdsecIdentityRolesService, error) {
	service, err := api.services.service(roles.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return roles.ServiceGenerator(api.loadServiceAuthenticators(roles.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*roles.IdsecIdentityRolesService), nil
}

func (api *IdsecAPI) IdentityUsers() (*users.IdsecIdentityUsersService, error) {
	service, err := api.services.service(users.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return users.ServiceGenerator(api.loadServiceAuthenticators(users.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*users.IdsecIdentityUsersService), nil
}

func (api *IdsecAPI) IdentityWebapps() (*webapps.IdsecIdentityWebappsService, error) {
	service, err := api.services.service(webapps.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return webapps.ServiceGenerator(api.loadServiceAuthenticators(webapps.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*webapps.IdsecIdentityWebappsService), nil
}

func (api *IdsecAPI) PamshAccounts() (*pamshaccounts.IdsecPamshAccountsService, error) {
	service, err := api.services.service(pamshaccounts.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return pamshaccounts.ServiceGenerator(api.loadServiceAuthenticators(pamshaccounts.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*pamshaccounts.IdsecPamshAccountsService), nil
}

func (api *IdsecAPI) PamshSafes() (*pamshsafes.IdsecPamshSafesService, error) {
	service, err := api.services.service(pamshsafes.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return pamshsafes.ServiceGenerator(api.loadServiceAuthenticators(pamshsafes.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*pamshsafes.IdsecPamshSafesService), nil
}

func (api *IdsecAPI) PcloudAccounts() (*accounts.IdsecPCloudAccountsService, error) {
	service, err := api.services.service(accounts.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return accounts.ServiceGenerator(api.loadServiceAuthenticators(accounts.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*accounts.IdsecPCloudAccountsService), nil
}

func (api *IdsecAPI) PcloudApplications() (*applications.IdsecPCloudApplicationsService, error) {
	service, err := api.services.service(applications.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return applications.ServiceGenerator(api.loadServiceAuthenticators(applications.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*applications.IdsecPCloudApplicationsService), nil
}

func (api *IdsecAPI) PcloudPlatforms() (*platforms.IdsecPCloudPlatformsService, error) {
	service, err := api.services.service(platforms.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return platforms.ServiceGenerator(api.loadServiceAuthenticators(platforms.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*platforms.IdsecPCloudPlatformsService), nil
}

func (api *IdsecAPI) PcloudSafes() (*safes.IdsecPCloudSafesService, error) {
	service, err := api.services.service(safes.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return safes.ServiceGenerator(api.loadServiceAuthenticators(safes.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*safes.IdsecPCloudSafesService), nil
}

func (api *IdsecAPI) PcloudTargetplatforms() (*targetplatforms.IdsecPCloudTargetPlatformsService, error) {
	service, err := api.services.service(targetplatforms.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return targetplatforms.ServiceGenerator(api.loadServiceAuthenticators(targetplatforms.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*targetplatforms.IdsecPCloudTargetPlatformsService), nil
}

func (api *IdsecAPI) PcloudUsergroups() (*usergroups.IdsecPCloudUserGroupsService, error) {
	service, err := api.services.service(usergroups.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return usergroups.ServiceGenerator(api.loadServiceAuthenticators(usergroups.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*usergroups.IdsecPCloudUserGroupsService), nil
}

func (api *IdsecAPI) PcloudUsers() (*users2.IdsecPCloudUsersService, error) {
	service, err := api.services.service(users2.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return users2.ServiceGenerator(api.loadServiceAuthenticators(users2.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*users2.IdsecPCloudUsersService), nil
}

func (api *IdsecAPI) Policy() (*policy.IdsecPolicyService, error) {
	service, err := api.services.service(policy.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return policy.ServiceGenerator(api.loadServiceAuthenticators(policy.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*policy.IdsecPolicyService), nil
}

func (api *IdsecAPI) PolicyCloudaccess() (*cloudaccess.IdsecPolicyCloudAccessService, error) {
	service, err := api.services.service(cloudaccess.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return cloudaccess.ServiceGenerator(api.loadServiceAuthenticators(cloudaccess.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*cloudaccess.IdsecPolicyCloudAccessService), nil
}

func (api *IdsecAPI) PolicyDb() (*db.IdsecPolicyDBService, error) {
	service, err := api.services.service(db.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return db.ServiceGenerator(api.loadServiceAuthenticators(db.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*db.IdsecPolicyDBService), nil
}

func (api *IdsecAPI) PolicyGroupaccess() (*groupaccess.IdsecPolicyGroupAccessService, error) {
	service, err := api.services.service(groupaccess.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return groupaccess.ServiceGenerator(api.loadServiceAuthenticators(groupaccess.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*groupaccess.IdsecPolicyGroupAccessService), nil
}

func (api *IdsecAPI) PolicyK8s() (*k8s.IdsecPolicyK8sService, error) {
	service, err := api.services.service(k8s.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return k8s.ServiceGenerator(api.loadServiceAuthenticators(k8s.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*k8s.IdsecPolicyK8sService), nil
}

func (api *IdsecAPI) PolicyVm() (*vm.IdsecPolicyVMService, error) {
	service, err := api.services.service(vm.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return vm.ServiceGenerator(api.loadServiceAuthenticators(vm.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*vm.IdsecPolicyVMService), nil
}

func (api *IdsecAPI) ScaCloudaccess() (*cloudaccess2.IdsecSCACloudAccessService, error) {
	service, err := api.services.service(cloudaccess2.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return cloudaccess2.ServiceGenerator(api.loadServiceAuthenticators(cloudaccess2.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*cloudaccess2.IdsecSCACloudAccessService), nil
}

func (api *IdsecAPI) ScaDiscovery() (*discovery.IdsecSCADiscoveryService, error) {
	service, err := api.services.service(discovery.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return discovery.ServiceGenerator(api.loadServiceAuthenticators(discovery.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*discovery.IdsecSCADiscoveryService), nil
}

func (api *IdsecAPI) ScaGroupaccess() (*groupaccess2.IdsecSCAGroupAccessService, error) {
	service, err := api.services.service(groupaccess2.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return groupaccess2.ServiceGenerator(api.loadServiceAuthenticators(groupaccess2.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*groupaccess2.IdsecSCAGroupAccessService), nil
}

func (api *IdsecAPI) ScaK8s() (*k8s2.IdsecSCAK8sService, error) {
	service, err := api.services.service(k8s2.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return k8s2.ServiceGenerator(api.loadServiceAuthenticators(k8s2.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*k8s2.IdsecSCAK8sService), nil
}

func (api *IdsecAPI) SechubConfigurations() (*configurations.IdsecSecHubConfigurationService, error) {
	service, err := api.services.service(configurations.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return configurations.ServiceGenerator(api.loadServiceAuthenticators(configurations.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*configurations.IdsecSecHubConfigurationService), nil
}

func (api *IdsecAPI) SechubFilters() (*filters.IdsecSecHubFiltersService, error) {
	service, err := api.services.service(filters.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return filters.ServiceGenerator(api.loadServiceAuthenticators(filters.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*filters.IdsecSecHubFiltersService), nil
}

func (api *IdsecAPI) SechubScans() (*scans.IdsecSecHubScansService, error) {
	service, err := api.services.service(scans.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return scans.ServiceGenerator(api.loadServiceAuthenticators(scans.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*scans.IdsecSecHubScansService), nil
}

func (api *IdsecAPI) SechubSecrets() (*secrets.IdsecSecHubSecretsService, error) {
	service, err := api.services.service(secrets.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return secrets.ServiceGenerator(api.loadServiceAuthenticators(secrets.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*secrets.IdsecSecHubSecretsService), nil
}

func (api *IdsecAPI) SechubSecretstores() (*secretstores.IdsecSecHubSecretStoresService, error) {
	service, err := api.services.service(secretstores.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return secretstores.ServiceGenerator(api.loadServiceAuthenticators(secretstores.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*secretstores.IdsecSecHubSecretStoresService), nil
}

func (api *IdsecAPI) SechubServiceinfo() (*serviceinfo.IdsecSecHubServiceInfoService, error) {
	service, err := api.services.service(serviceinfo.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return serviceinfo.ServiceGenerator(api.loadServiceAuthenticators(serviceinfo.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*serviceinfo.IdsecSecHubServiceInfoService), nil
}

func (api *IdsecAPI) SechubSyncpolicies() (*syncpolicies.IdsecSecHubSyncPoliciesService, error) {
	service, err := api.services.service(syncpolicies.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return syncpolicies.ServiceGenerator(api.loadServiceAuthenticators(syncpolicies.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*syncpolicies.IdsecSecHubSyncPoliciesService), nil
}

func (api *IdsecAPI) SiaAccess() (*access.IdsecSIAAccessService, error) {
	service, err := api.services.service(access.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return access.ServiceGenerator(api.loadServiceAuthenticators(access.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*access.IdsecSIAAccessService), nil
}

func (api *IdsecAPI) SiaCertificates() (*certificates.IdsecSIACertificatesService, error) {
	service, err := api.services.service(certificates.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return certificates.ServiceGenerator(api.loadServiceAuthenticators(certificates.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*certificates.IdsecSIACertificatesService), nil
}

func (api *IdsecAPI) SiaDb() (*db2.IdsecSIADBService, error) {
	service, err := api.services.service(db2.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return db2.ServiceGenerator(api.loadServiceAuthenticators(db2.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*db2.IdsecSIADBService), nil
}

func (api *IdsecAPI) SiaDbstrongaccounts() (*dbstrongaccounts.IdsecSIADBStrongAccountsService, error) {
	service, err := api.services.service(dbstrongaccounts.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return dbstrongaccounts.ServiceGenerator(api.loadServiceAuthenticators(dbstrongaccounts.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*dbstrongaccounts.IdsecSIADBStrongAccountsService), nil
}

func (api *IdsecAPI) SiaDoctor() (*doctor.IdsecSIADoctorService, error) {
	service, err := api.services.service(doctor.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return doctor.ServiceGenerator(api.loadServiceAuthenticators(doctor.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*doctor.IdsecSIADoctorService), nil
}

func (api *IdsecAPI) SiaK8s() (*k8s3.IdsecSIAK8SService, error) {
	service, err := api.services.service(k8s3.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return k8s3.ServiceGenerator(api.loadServiceAuthenticators(k8s3.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*k8s3.IdsecSIAK8SService), nil
}

func (api *IdsecAPI) SiaSecretsdb() (*dbsecrets.IdsecSIASecretsDBService, error) {
	service, err := api.services.service(dbsecrets.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return dbsecrets.ServiceGenerator(api.loadServiceAuthenticators(dbsecrets.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*dbsecrets.IdsecSIASecretsDBService), nil
}

func (api *IdsecAPI) SiaSecretsvm() (*vmsecrets.IdsecSIASecretsVMService, error) {
	service, err := api.services.service(vmsecrets.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return vmsecrets.ServiceGenerator(api.loadServiceAuthenticators(vmsecrets.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*vmsecrets.IdsecSIASecretsVMService), nil
}

func (api *IdsecAPI) SiaSettings() (*settings.IdsecSIASettingsService, error) {
	service, err := api.services.service(settings.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return settings.ServiceGenerator(api.loadServiceAuthenticators(settings.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*settings.IdsecSIASettingsService), nil
}

func (api *IdsecAPI) SiaShortenedconnectionstring() (*shortenedconnectionstring.IdsecSIAShortenedConnectionStringService, error) {
	service, err := api.services.service(shortenedconnectionstring.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return shortenedconnectionstring.ServiceGenerator(api.loadServiceAuthenticators(shortenedconnectionstring.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*shortenedconnectionstring.IdsecSIAShortenedConnectionStringService), nil
}

func (api *IdsecAPI) SiaSsh() (*ssh.IdsecSIASSHService, error) {
	service, err := api.services.service(ssh.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return ssh.ServiceGenerator(api.loadServiceAuthenticators(ssh.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*ssh.IdsecSIASSHService), nil
}

func (api *IdsecAPI) SiaSshca() (*sshca.IdsecSIASSHCAService, error) {
	service, err := api.services.service(sshca.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return sshca.ServiceGenerator(api.loadServiceAuthenticators(sshca.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*sshca.IdsecSIASSHCAService), nil
}

func (api *IdsecAPI) SiaSso() (*sso.IdsecSIASSOService, error) {
	service, err := api.services.service(sso.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return sso.ServiceGenerator(api.loadServiceAuthenticators(sso.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*sso.IdsecSIASSOService), nil
}

func (api *IdsecAPI) SiaWorkspacesdb() (*db3.IdsecSIAWorkspacesDBService, error) {
	service, err := api.services.service(db3.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return db3.ServiceGenerator(api.loadServiceAuthenticators(db3.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*db3.IdsecSIAWorkspacesDBService), nil
}

func (api *IdsecAPI) SiaWorkspacestargetsets() (*targetsets.IdsecSIAWorkspacesTargetSetsService, error) {
	service, err := api.services.service(targetsets.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return targetsets.ServiceGenerator(api.loadServiceAuthenticators(targetsets.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*targetsets.IdsecSIAWorkspacesTargetSetsService), nil
}

func (api *IdsecAPI) SmSessionactivities() (*sessionactivities.IdsecSMSessionActivitiesService, error) {
	service, err := api.services.service(sessionactivities.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return sessionactivities.ServiceGenerator(api.loadServiceAuthenticators(sessionactivities.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*sessionactivities.IdsecSMSessionActivitiesService), nil
}

func (api *IdsecAPI) SmSessions() (*sessions.IdsecSMSessionsService, error) {
	service, err := api.services.service(sessions.ServiceConfig.ServiceName, func() (services.IdsecService, error) {
		return sessions.ServiceGenerator(api.loadServiceAuthenticators(sessions.ServiceConfig)...)
	})
	if err != nil {
		return nil, err
	}
	return (*service).(*sessions.IdsecSMSessionsService), nil
}
