// Package api provides the main IDSEC SDK API interface for accessing all IDSEC services
// Code generated by genservices; DO NOT EDIT.
// Automatically generated Idsec API for all SDK services.
// Each service can define a module init to register its config alongside a ServiceGenerator function
// in the IDSEC SDK Golang. This package serves as the central entry point for interacting
// with various IDSEC services including SIA, SecHub, PCloud, Identity, and other components.
//
// The IdsecAPI struct acts as a service factory and registry, managing authenticators,
// service instances, and configuration profiles. It provides lazy loading of services,
// meaning services are only instantiated when first accessed, and subsequent calls
// return the cached instance.
//
// Key features:
//   - Centralized access to all IDSEC services
//   - Lazy loading and caching of service instances
//   - Authenticator management and distribution to services
//   - Profile-based configuration management
//   - Service dependency injection with authenticators
//   - Consistent error handling across all services
//
// The API supports multiple authenticators that are automatically distributed to
// services based on their configuration requirements. Each service specifies
// required and optional authenticators, and the API ensures the appropriate
// authenticators are provided during service initialization.
//
// Example:
//
//	// Create authenticators
//	ispAuth := &auth.IdsecISPAuth{...}
//	authenticators := []auth.IdsecAuth{ispAuth}
//
//	// Create API instance
//	api, err := NewIdsecAPI(authenticators, nil) // nil uses default profile
//	if err != nil {
//		// handle error
//	}
//
//	// Access services (lazy loaded)
//	ssoService, err := api.SiaSso()
//	if err != nil {
//		// handle error
//	}
//
//	// Get specific authenticator
//	auth, err := api.Authenticator("isp")
//	if err != nil {
//		// handle error
//	}
package api

import (
	"fmt"

	"github.com/cyberark/idsec-sdk-golang/pkg/auth"
	"github.com/cyberark/idsec-sdk-golang/pkg/models"
	"github.com/cyberark/idsec-sdk-golang/pkg/profiles"
	"github.com/cyberark/idsec-sdk-golang/pkg/services"

	aws "github.com/cyberark/idsec-sdk-golang/pkg/services/cce/aws"
	azure "github.com/cyberark/idsec-sdk-golang/pkg/services/cce/azure"
	cmgr "github.com/cyberark/idsec-sdk-golang/pkg/services/cmgr"
	directories "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/directories"
	roles "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/roles"
	users "github.com/cyberark/idsec-sdk-golang/pkg/services/identity/users"
	accounts "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/accounts"
	platforms "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/platforms"
	safes "github.com/cyberark/idsec-sdk-golang/pkg/services/pcloud/safes"
	policy "github.com/cyberark/idsec-sdk-golang/pkg/services/policy"
	cloudaccess "github.com/cyberark/idsec-sdk-golang/pkg/services/policy/cloudaccess"
	sca "github.com/cyberark/idsec-sdk-golang/pkg/services/sca"
	configuration "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/configuration"
	filters "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/filters"
	scans "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/scans"
	secrets "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/secrets"
	secretstores "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/secretstores"
	serviceinfo "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/serviceinfo"
	syncpolicies "github.com/cyberark/idsec-sdk-golang/pkg/services/sechub/syncpolicies"
	access "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/access"
	certificates "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/certificates"
	db "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/db"
	k8s "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/k8s"
	dbsecrets "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/secrets/db"
	vmsecrets "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/secrets/vm"
	settings "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/settings"
	shortenedconnectionstring "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/shortenedconnectionstring"
	sshca "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/sshca"
	sso "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/sso"
	db2 "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/workspaces/db"
	targetsets "github.com/cyberark/idsec-sdk-golang/pkg/services/sia/workspaces/targetsets"
	sm "github.com/cyberark/idsec-sdk-golang/pkg/services/sm"
	uap "github.com/cyberark/idsec-sdk-golang/pkg/services/uap"
	db3 "github.com/cyberark/idsec-sdk-golang/pkg/services/uap/sia/db"
	vm "github.com/cyberark/idsec-sdk-golang/pkg/services/uap/sia/vm"
)

// IdsecAPI wraps different API functionality of Idsec Services.
//
// IdsecAPI serves as the central entry point and service factory for all IDSEC services.
// It manages authenticators, service instances, and configuration profiles, providing
// a unified interface for accessing various IDSEC components including SIA, SecHub,
// PCloud, Identity, and other services.
//
// The struct implements lazy loading for services - each service is only instantiated
// when first accessed through its corresponding method. Subsequent calls return the
// cached instance, ensuring efficient resource usage and consistent service state.
//
// Service creation follows a dependency injection pattern where authenticators are
// automatically distributed to services based on their configuration requirements.
// Each service specifies required and optional authenticators, and IdsecAPI ensures
// the appropriate authenticators are provided during initialization.
type IdsecAPI struct {
	authenticators []auth.IdsecAuth
	services       map[string]*services.IdsecService
	profile        *models.IdsecProfile
}

// NewIdsecAPI creates a new IdsecAPI instance with the provided authenticators and profile.
//
// Initializes a new IdsecAPI instance that serves as the central access point for all
// IDSEC services. The instance manages the provided authenticators and distributes them
// to services as needed. If no profile is provided (nil), the default profile is
// loaded automatically.
//
// The services map is initialized empty and services are created lazily when first
// accessed through their respective getter methods. This approach ensures optimal
// resource usage and faster startup times.
//
// Parameters:
//   - authenticators: Slice of authenticators to be used by services. Each service
//     will receive the authenticators it requires based on its configuration
//   - profile: Configuration profile to use. If nil, the default profile is loaded
//     automatically using the default profile loader
//
// Returns a pointer to the initialized IdsecAPI instance, or an error if the default
// profile cannot be loaded when profile is nil.
//
// Example:
//
//	// With explicit profile
//	profile := &models.IdsecProfile{...}
//	api, err := NewIdsecAPI(authenticators, profile)
//
//	// With default profile (recommended)
//	api, err := NewIdsecAPI(authenticators, nil)
//	if err != nil {
//		// handle profile loading error
//	}
func NewIdsecAPI(authenticators []auth.IdsecAuth, profile *models.IdsecProfile) (*IdsecAPI, error) {
	var err error
	if profile == nil {
		profile, err = (*profiles.DefaultProfilesLoader()).LoadDefaultProfile()
		if err != nil {
			return nil, err
		}
	}
	return &IdsecAPI{
		authenticators: authenticators,
		services:       make(map[string]*services.IdsecService),
		profile:        profile,
	}, nil
}

// loadServiceAuthenticators filters and returns authenticators required by a service configuration.
//
// This internal method processes the API's authenticator collection and returns only
// those authenticators that are required or optional for the specified service.
// Required authenticators are processed first, followed by optional authenticators.
//
// The method ensures that services receive only the authenticators they need,
// following the dependency injection pattern. This approach provides better
// security isolation and cleaner service initialization.
//
// Parameters:
//   - config: Service configuration specifying required and optional authenticator names
//
// Returns a slice of authenticators that match the service's requirements.
// If no matching authenticators are found, returns an empty slice.
func (api *IdsecAPI) loadServiceAuthenticators(config services.IdsecServiceConfig) []auth.IdsecAuth {
	var authenticators []auth.IdsecAuth
	for _, authenticator := range api.authenticators {
		for _, name := range config.RequiredAuthenticatorNames {
			if authenticator.AuthenticatorName() == name {
				authenticators = append(authenticators, authenticator)
			}
		}
	}
	for _, authenticator := range api.authenticators {
		for _, name := range config.OptionalAuthenticatorNames {
			if authenticator.AuthenticatorName() == name {
				authenticators = append(authenticators, authenticator)
			}
		}
	}
	return authenticators
}

// Authenticator returns the authenticator with the specified name from the IdsecAPI instance.
//
// Searches through the API's authenticator collection and returns the first
// authenticator that matches the specified name. This method provides access
// to specific authenticators for custom operations or debugging purposes.
//
// The search is case-sensitive and matches the exact authenticator name as
// returned by the authenticator's AuthenticatorName() method.
//
// Parameters:
//   - authenticatorName: The exact name of the authenticator to retrieve
//
// Returns the matching authenticator, or an error if no authenticator with
// the specified name is found.
//
// Example:
//
//	ispAuth, err := api.Authenticator("isp")
//	if err != nil {
//		// handle authenticator not found
//	}
//	// use ispAuth for custom operations
func (api *IdsecAPI) Authenticator(authenticatorName string) (auth.IdsecAuth, error) {
	for _, authenticator := range api.authenticators {
		if authenticator.AuthenticatorName() == authenticatorName {
			return authenticator, nil
		}
	}
	return nil, fmt.Errorf("%s is not supported or not found", authenticatorName)
}

// Profile returns the profile associated with the IdsecAPI instance.
//
// Provides access to the configuration profile that was set during API initialization.
// The profile contains environment-specific settings, endpoints, and other configuration
// parameters used by the various IDSEC services.
//
// The returned profile is the same instance that was either explicitly provided to
// NewIdsecAPI or automatically loaded as the default profile when nil was passed.
//
// Returns a pointer to the IdsecProfile instance. The profile is never nil for a
// properly initialized IdsecAPI instance.
//
// Example:
//
//	profile := api.Profile()
//	fmt.Printf("Using profile: %s\n", profile.ProfileName)
func (api *IdsecAPI) Profile() *models.IdsecProfile {
	return api.profile
}

func (api *IdsecAPI) CceAws() (*aws.IdsecCCEAWSService, error) {
	if serviceIfs, ok := api.services[aws.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*aws.IdsecCCEAWSService), nil
	}
	service, err := aws.ServiceGenerator(api.loadServiceAuthenticators(aws.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[aws.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) CceAzure() (*azure.IdsecCCEAzureService, error) {
	if serviceIfs, ok := api.services[azure.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*azure.IdsecCCEAzureService), nil
	}
	service, err := azure.ServiceGenerator(api.loadServiceAuthenticators(azure.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[azure.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) Cmgr() (*cmgr.IdsecCmgrService, error) {
	if serviceIfs, ok := api.services[cmgr.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*cmgr.IdsecCmgrService), nil
	}
	service, err := cmgr.ServiceGenerator(api.loadServiceAuthenticators(cmgr.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[cmgr.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) IdentityDirectories() (*directories.IdsecIdentityDirectoriesService, error) {
	if serviceIfs, ok := api.services[directories.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*directories.IdsecIdentityDirectoriesService), nil
	}
	service, err := directories.ServiceGenerator(api.loadServiceAuthenticators(directories.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[directories.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) IdentityRoles() (*roles.IdsecIdentityRolesService, error) {
	if serviceIfs, ok := api.services[roles.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*roles.IdsecIdentityRolesService), nil
	}
	service, err := roles.ServiceGenerator(api.loadServiceAuthenticators(roles.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[roles.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) IdentityUsers() (*users.IdsecIdentityUsersService, error) {
	if serviceIfs, ok := api.services[users.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*users.IdsecIdentityUsersService), nil
	}
	service, err := users.ServiceGenerator(api.loadServiceAuthenticators(users.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[users.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) PcloudAccounts() (*accounts.IdsecPCloudAccountsService, error) {
	if serviceIfs, ok := api.services[accounts.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*accounts.IdsecPCloudAccountsService), nil
	}
	service, err := accounts.ServiceGenerator(api.loadServiceAuthenticators(accounts.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[accounts.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) PcloudPlatforms() (*platforms.IdsecPCloudPlatformsService, error) {
	if serviceIfs, ok := api.services[platforms.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*platforms.IdsecPCloudPlatformsService), nil
	}
	service, err := platforms.ServiceGenerator(api.loadServiceAuthenticators(platforms.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[platforms.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) PcloudSafes() (*safes.IdsecPCloudSafesService, error) {
	if serviceIfs, ok := api.services[safes.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*safes.IdsecPCloudSafesService), nil
	}
	service, err := safes.ServiceGenerator(api.loadServiceAuthenticators(safes.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[safes.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) Policy() (*policy.IdsecPolicyService, error) {
	if serviceIfs, ok := api.services[policy.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*policy.IdsecPolicyService), nil
	}
	service, err := policy.ServiceGenerator(api.loadServiceAuthenticators(policy.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[policy.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) PolicyCloudaccess() (*cloudaccess.IdsecPolicyCloudAccessService, error) {
	if serviceIfs, ok := api.services[cloudaccess.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*cloudaccess.IdsecPolicyCloudAccessService), nil
	}
	service, err := cloudaccess.ServiceGenerator(api.loadServiceAuthenticators(cloudaccess.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[cloudaccess.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) Sca() (*sca.IdsecSCAService, error) {
	if serviceIfs, ok := api.services[sca.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sca.IdsecSCAService), nil
	}
	service, err := sca.ServiceGenerator(api.loadServiceAuthenticators(sca.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[sca.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SechubConfiguration() (*configuration.IdsecSecHubConfigurationService, error) {
	if serviceIfs, ok := api.services[configuration.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*configuration.IdsecSecHubConfigurationService), nil
	}
	service, err := configuration.ServiceGenerator(api.loadServiceAuthenticators(configuration.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[configuration.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SechubFilters() (*filters.IdsecSecHubFiltersService, error) {
	if serviceIfs, ok := api.services[filters.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*filters.IdsecSecHubFiltersService), nil
	}
	service, err := filters.ServiceGenerator(api.loadServiceAuthenticators(filters.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[filters.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SechubScans() (*scans.IdsecSecHubScansService, error) {
	if serviceIfs, ok := api.services[scans.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*scans.IdsecSecHubScansService), nil
	}
	service, err := scans.ServiceGenerator(api.loadServiceAuthenticators(scans.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[scans.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SechubSecrets() (*secrets.IdsecSecHubSecretsService, error) {
	if serviceIfs, ok := api.services[secrets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*secrets.IdsecSecHubSecretsService), nil
	}
	service, err := secrets.ServiceGenerator(api.loadServiceAuthenticators(secrets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[secrets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SechubSecretstores() (*secretstores.IdsecSecHubSecretStoresService, error) {
	if serviceIfs, ok := api.services[secretstores.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*secretstores.IdsecSecHubSecretStoresService), nil
	}
	service, err := secretstores.ServiceGenerator(api.loadServiceAuthenticators(secretstores.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[secretstores.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SechubServiceinfo() (*serviceinfo.IdsecSecHubServiceInfoService, error) {
	if serviceIfs, ok := api.services[serviceinfo.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*serviceinfo.IdsecSecHubServiceInfoService), nil
	}
	service, err := serviceinfo.ServiceGenerator(api.loadServiceAuthenticators(serviceinfo.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[serviceinfo.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SechubSyncpolicies() (*syncpolicies.IdsecSecHubSyncPoliciesService, error) {
	if serviceIfs, ok := api.services[syncpolicies.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*syncpolicies.IdsecSecHubSyncPoliciesService), nil
	}
	service, err := syncpolicies.ServiceGenerator(api.loadServiceAuthenticators(syncpolicies.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[syncpolicies.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaAccess() (*access.IdsecSIAAccessService, error) {
	if serviceIfs, ok := api.services[access.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*access.IdsecSIAAccessService), nil
	}
	service, err := access.ServiceGenerator(api.loadServiceAuthenticators(access.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[access.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaCertificates() (*certificates.IdsecSIACertificatesService, error) {
	if serviceIfs, ok := api.services[certificates.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*certificates.IdsecSIACertificatesService), nil
	}
	service, err := certificates.ServiceGenerator(api.loadServiceAuthenticators(certificates.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[certificates.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaDb() (*db.IdsecSIADBService, error) {
	if serviceIfs, ok := api.services[db.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*db.IdsecSIADBService), nil
	}
	service, err := db.ServiceGenerator(api.loadServiceAuthenticators(db.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[db.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaK8s() (*k8s.IdsecSIAK8SService, error) {
	if serviceIfs, ok := api.services[k8s.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*k8s.IdsecSIAK8SService), nil
	}
	service, err := k8s.ServiceGenerator(api.loadServiceAuthenticators(k8s.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[k8s.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaSecretsDb() (*dbsecrets.IdsecSIASecretsDBService, error) {
	if serviceIfs, ok := api.services[dbsecrets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*dbsecrets.IdsecSIASecretsDBService), nil
	}
	service, err := dbsecrets.ServiceGenerator(api.loadServiceAuthenticators(dbsecrets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[dbsecrets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaSecretsVm() (*vmsecrets.IdsecSIASecretsVMService, error) {
	if serviceIfs, ok := api.services[vmsecrets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*vmsecrets.IdsecSIASecretsVMService), nil
	}
	service, err := vmsecrets.ServiceGenerator(api.loadServiceAuthenticators(vmsecrets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[vmsecrets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaSettings() (*settings.IdsecSIASettingsService, error) {
	if serviceIfs, ok := api.services[settings.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*settings.IdsecSIASettingsService), nil
	}
	service, err := settings.ServiceGenerator(api.loadServiceAuthenticators(settings.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[settings.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaShortenedconnectionstring() (*shortenedconnectionstring.IdsecSIAShortenedConnectionStringService, error) {
	if serviceIfs, ok := api.services[shortenedconnectionstring.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*shortenedconnectionstring.IdsecSIAShortenedConnectionStringService), nil
	}
	service, err := shortenedconnectionstring.ServiceGenerator(api.loadServiceAuthenticators(shortenedconnectionstring.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[shortenedconnectionstring.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaSshca() (*sshca.IdsecSIASSHCAService, error) {
	if serviceIfs, ok := api.services[sshca.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sshca.IdsecSIASSHCAService), nil
	}
	service, err := sshca.ServiceGenerator(api.loadServiceAuthenticators(sshca.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[sshca.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaSso() (*sso.IdsecSIASSOService, error) {
	if serviceIfs, ok := api.services[sso.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sso.IdsecSIASSOService), nil
	}
	service, err := sso.ServiceGenerator(api.loadServiceAuthenticators(sso.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[sso.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaWorkspacesDb() (*db2.IdsecSIAWorkspacesDBService, error) {
	if serviceIfs, ok := api.services[db2.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*db2.IdsecSIAWorkspacesDBService), nil
	}
	service, err := db2.ServiceGenerator(api.loadServiceAuthenticators(db2.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[db2.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) SiaWorkspacesTargetsets() (*targetsets.IdsecSIAWorkspacesTargetSetsService, error) {
	if serviceIfs, ok := api.services[targetsets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*targetsets.IdsecSIAWorkspacesTargetSetsService), nil
	}
	service, err := targetsets.ServiceGenerator(api.loadServiceAuthenticators(targetsets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[targetsets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) Sm() (*sm.IdsecSMService, error) {
	if serviceIfs, ok := api.services[sm.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sm.IdsecSMService), nil
	}
	service, err := sm.ServiceGenerator(api.loadServiceAuthenticators(sm.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[sm.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) Uap() (*uap.IdsecUAPService, error) {
	if serviceIfs, ok := api.services[uap.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*uap.IdsecUAPService), nil
	}
	service, err := uap.ServiceGenerator(api.loadServiceAuthenticators(uap.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[uap.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) UapDb() (*db3.IdsecUAPSIADBService, error) {
	if serviceIfs, ok := api.services[db3.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*db3.IdsecUAPSIADBService), nil
	}
	service, err := db3.ServiceGenerator(api.loadServiceAuthenticators(db3.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[db3.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *IdsecAPI) UapVm() (*vm.IdsecUAPSIAVMService, error) {
	if serviceIfs, ok := api.services[vm.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*vm.IdsecUAPSIAVMService), nil
	}
	service, err := vm.ServiceGenerator(api.loadServiceAuthenticators(vm.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.IdsecService = service
	api.services[vm.ServiceConfig.ServiceName] = &baseService
	return service, nil
}
